# Generated by Django 4.2.6 on 2023-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('releaseddate', models.DateField()),
                ('characters', models.CharField(max_length=50)),
                ('theatrename', models.CharField(max_length=50)),
                ('directorname', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
    ]
