# Generated by Django 4.2.6 on 2023-10-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_moviemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=50)),
                ('bookingdate', models.DateField()),
                ('hotelimage', models.ImageField(upload_to='')),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
