# Generated by Django 4.2.6 on 2023-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0007_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='personmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
