# Generated by Django 4.2.6 on 2023-10-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_personmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
