# Generated by Django 4.2.6 on 2023-11-01 03:50

from django.db import migrations, models
import restapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0010_filesupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='taskname',
            field=models.CharField(max_length=50, validators=[restapp.models.func]),
        ),
    ]
