# Generated by Django 4.2.6 on 2023-11-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0013_customermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customermodel',
        ),
    ]
